- name: openai/claude-3.5-sonnet
  edit_format: diff
  weak_model_name: openai/claude-3.5-sonnet
  use_repo_map: true
  examples_as_sys_msg: true
  extra_params:
    max_tokens: 8192
  cache_control: true
  editor_model_name: openai/claude-3.5-sonnet
  editor_edit_format: editor-diff